config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #                                 registrations: 'users/registrations',
  #                                 sessions: 'users/sessions'
  #                               }

  resources :registrations
  resources :sessions
  resources :password
  resource :password_reset

  patch '/id/:id/edit', to: 'registrations#update', as: :edit_user_info

  resources :games

  root to: 'home#home'

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get 'games', to: 'games#index'
        get 'games/:id', to: 'games#show'
        get 'id/:id', to: 'profiles#show'
      end
    end
  end


  patch '/games/:id/choose_winner', to: 'games#choose_winner', as: :choose_winner
  post '/games/:id', to: 'participants#create', as: :game_participants
  get '/id/:id', to: 'profiles#show', as: :user_profile
  get '/id/:id/friends', to: 'profiles#friends', as: :user_friends
  post '/id/:id', to: 'friendships#create', as: :user_friendships
  patch '/id/:id', to: 'friendships#update', as: :friendship
  delete '/notification/:id', to: 'notifications#destroy', as: :notification_destroy

  post '/games/:id/game_invites', to: 'notifications#create_user_invite', as: :game_invites

  post '/game_invites/:id/accept', to: 'notifications#accept_invite', as: :accept_invite
  delete '/game_invites/:id/decline', to: 'notifications#decline_invite', as: :decline_invite

  post  '/frienships/create', to: 'notifications#send_friendship_request', as: :send_friendship_request
  patch '/friendships/:id/accept', to: 'notifications#accept_friendship', as: :accept_friendship
  patch '/friendships/:id/decline', to: 'notifications#decline_friendship', as: :decline_friendship

  # oauth
  get '/auth/discord/callback', to: 'omniauth#discord', as: :discord_login
  get '/auth/github/callback', to: 'omniauth#github', as: :github_login

  # webhooks

  get 'pricing', to: 'stripe/checkout#pricing'
  post 'stripe/webhooks', to: 'stripe/webhooks#create'
  post 'stripe/checkout', to: 'stripe/checkout#create'
  get 'stripe/success', to: 'stripe/checkout#success'
  get 'stripe/failure', to: 'stripe/checkout#failure'
  post 'stripe/billing_portal', to: 'stripe/billing_portal#create'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :subject, polymorphic: true
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController # :nodoc:
  include ActionView::RecordIdentifier

  before_action :authenticate_user

  def create_user_invite
    @game_invite = GameInvite.create!(user_invite_params)
    @notification = @game_invite.notification
    @user = @game_invite.receiver
    @game = @game_invite.game
    @eligible_friends = []

    @eligible_friends = @user.find_eligible_friends_for_game(@game) if @user

    respond_to do |format|
      if @game_invite
        update_notification_counter
        send_notification_to_receiver
        add_pulsive_element
        remove_notification_possibility_for_users
        format.turbo_stream
        # format.html { redirect_to @game_invite.game, notice: "Successfully send to #{@game_invite.receiver.username}" }
      end
    end
  end

  def accept_invite
    @game_invite = GameInvite.find(params[:id])
    @notification = @game_invite.notification
    @user = @game_invite.receiver
    @game = @game_invite.game

    @participant = @game_invite.accept

    respond_to do |format|
      if @participant
        stream_remove_pulsive_element if @user.notifications.count.zero?
        format.html { redirect_to @game, notice: 'Successfully accepted invite', data: { turbo: false } }
        participants_list_stream
        win_selector_stream
        game_member_counter_stream
      else
        @game_invite.decline
        format.html { redirect_to Game, alert: 'Game already full or end' }
      end
    end
  end

  def decline_invite
    @game_invite = GameInvite.find(params[:id])
    @notification = @game_invite.notification

    @user = @game_invite.receiver
    @game = @game_invite.game

    respond_to do |format|
      if @game_invite.decline
        puts @user.notifications.count
        puts @user.notifications.count.zero?

        stream_remove_pulsive_element if @user.notifications.count.zero?
        format.turbo_stream do
          render turbo_stream: [
            update_local_notification_counter,
            remove_user_notification
          ]
        end
      end
    end
  end

  def send_friendship_request
    @friendship = Friendship.new params.required(:friendship).permit(:receiver_id, :sender_id)
    @friendship.pending!
    @user = @friendship.receiver

    respond_to do |format|
      if @friendship.save
        @notification = @friendship.notification
        send_notification_to_receiver
        update_notification_counter
        add_pulsive_element
        format.html { redirect_to "/id/#{@user.id}", notice: 'Friend request was successfully send', data: { turbo: false } }
      end
    end
  end

  def accept_friendship
    @friendship = Friendship.find(params[:id])
    @notification = @friendship.notification
    @user = @friendship.receiver

    authorize @user, :user?

    @friendship.accept

    respond_to do |format|
      if @friendship.accepted?
        stream_remove_pulsive_element if @user.notifications.count.zero?
        format.turbo_stream do
          render turbo_stream: [
            remove_user_notification,
            update_local_notification_counter
          ]
        end
        add_new_friendship_to_list
      end
    end
  end

  def decline_friendship
    @friendship = Friendship.find(params[:id])
    @notification = @friendship.notification

    @user = @friendship.receiver

    authorize @user, :user?

    @friendship.decline
    @user = User.find(@friendship.receiver.id)

    respond_to do |format|
      stream_remove_pulsive_element if @user.notifications.count.zero?
      format.turbo_stream do
        render turbo_stream: [
          remove_user_notification,
          update_local_notification_counter
        ]
      end
    end
  end

  private

  def add_pulsive_element
    if @user.notifications.count <= 1
      Turbo::StreamsChannel.broadcast_prepend_to "#{dom_id(@user)}_notifications", target: 'notification_button', partial: 'layouts/pulsive_element'
    end
  end

  def stream_remove_pulsive_element
    Turbo::StreamsChannel.broadcast_remove_to "#{dom_id(@user)}_notifications", target: 'notification_pulsing_element'
  end

  def participants_list_stream
    Turbo::StreamsChannel.broadcast_append_to "#{dom_id(@game)}", target: 'participants', partial: 'participants/participant', locals: { participant: @participant, game: @game }
  end

  def win_selector_stream
    Turbo::StreamsChannel.broadcast_update_to "#{dom_id(@game)}", target: 'win_selector', partial: 'participants/win_selector', locals: { participants: @game.participants , game: @game }
  end

  def game_member_counter_stream
    Turbo::StreamsChannel.broadcast_update_to 'games', target: 'participants_counter', html: @game.participants.count
    Turbo::StreamsChannel.broadcast_update_to "#{dom_id(@game)}", target: 'participants_counter', html: @game.participants.count
  end

  def send_notification_to_receiver
    Turbo::StreamsChannel.broadcast_append_to "#{dom_id(@user)}_notifications", target: 'notifications', partial: "notifications/notification_classifying", locals: { notification: @notification }
  end

  def update_notification_counter
    Turbo::StreamsChannel.broadcast_update_to "#{dom_id(@user)}_notifications", target: 'notification_counter', html: @user.notifications.count
  end

  def update_local_notification_counter
    turbo_stream.update 'notification_counter', html: @user.notifications.count
  end

  def remove_user_notification
    turbo_stream.remove "#{dom_id(@notification)}_notification"
  end

  def add_new_friendship_to_list
    Turbo::StreamsChannel.broadcast_append_to "#{dom_id(@friendship.receiver)}_friendships", target: "friendships", partial: "friendships/friendship", locals: { friendship: @friendship, user: @user }
  end

  def add_notification_possibility_for_users
    @notification.receiver.friends_who_participates_in_game(@game).each do |id|
      user = User.find(id)
      Turbo::StreamsChannel.broadcast_replace_to "#{dom_id(@game)}_#{dom_id(user)}_friends", target: "#{dom_id(user)}_friends", partial: "games/notifications/invite_friends", locals: { user: user, friends: user.find_eligible_friends_for_game(@game), game: @game }
    end
  end

  def remove_notification_possibility_for_users
    @user.friends_who_participates_in_game(@game).each do |id|
      user = User.find(id)
      Turbo::StreamsChannel.broadcast_remove_to "#{dom_id(@game)}_#{dom_id(user)}_friends", target: "#{dom_id(@user)}"
    end
  end

  def user_invite_params
    params.require(:game_invite).permit(:sender_id, :receiver_id, :game_id, :desc)
  end

  def full?(game)
    game.participants.count >= game.members
  end

  def authenticate_user
    return if user_signed_in?

    redirect_to new_session_path, status: :found, alert: 'You must be loged in to perform this action'
  end

end

app/views/notifications/_friendship_notification.html.erb
<div class = 'py-2'>
  <div id = "<%= dom_id(friendship.sender)%>_avatar" class = 'flex flex-row items-center '>
  <% if friendship.sender&.avatar&.attached? %>
      <%= link_to (image_tag friendship.sender.avatar, class: "avatar"), "/id/#{friendship.sender_id}", data: {turbo: false}%>
    <% else %>
      <%= link_to (image_tag "guestavatar1.png", class: "avatar"), "/id/#{friendship.sender_id}", data: {turbo: false} %>
    <% end %>
  <span class = 'ml-2'> <%= friendship.sender.username %> send you a friendship request! </span>
  </div>

  <div id = "<%=dom_id(friendship.sender)%>_buttons" class = 'flex flex-row' >
    <%= form_with(model: friendship, method: "patch", url: accept_friendship_path(friendship)) do |form| %>
        <%= form.hidden_field :status, value: 1 %>
        <%= form.submit 'Accept', class: 'transition ease-in-out delay-50 px-4 py-1 ml-16 mr-16 rounded-none bg-green-600 hover:scale-110 hover:bg-green-500 duration-300'%>
    <% end %>
    <%= form_with(model: friendship, method: "patch", url: decline_friendship_path(friendship)) do |form| %>
        <%= form.hidden_field :status, value: 0%>
        <%= form.submit 'Decline', class: 'transition ease-in-out delay-50 px-4 py-1 mx-4 rounded-none bg-red-500 hover:scale-110 hover:bg-red-600 duration-300' %>
    <% end %>
  </div>
</div>

app/views/notifications/_game_invite_notification.html.erb
<div>
  <div class = 'flex flex-row'>

  <div id = 'avatar'>
  <% if sender&.avatar&.attached? %>
    <%=link_to (image_tag (sender.avatar),
                      class: "avatar"),
                      "/id/#{sender.id}",
                      data: { turbo: :false } %>
  <% else %>
    <%= link_to (image_tag "guestavatar1.png",
                            class: "avatar"),
                            "/id/#{sender.id}",
                            data: { turbo: :false }%>
  <% end %>
  </div>

  <span id = 'text' class = 'pl-2'>
    <%= sender.username%> invited you to play
    <%= link_to game.name, game, data: { turbo: :false }%>
  </span>

  </div>

  <div id = 'buttons' class = 'flex flex-row'>
  <%= button_to "Accpet", accept_invite_path(notification.id), data: { turbo: :false }, class: 'transition ease-in-out delay-50 px-4 py-1 ml-16 mr-16 rounded-none bg-green-600 hover:scale-110 hover:bg-green-500 duration-300'%>

  <%= button_to "Decline", decline_invite_path(notification.id), method: :delete, class: 'transition ease-in-out delay-50 px-4 py-1 mx-4 rounded-none bg-red-500 hover:scale-110 hover:bg-red-600 duration-300'%>
  </div>
</div>

app/views/notifications/_notification.html.erb
<% if participant %>
<div>
  <% if unread %>
    <span> Unread </span>
  <% end %>
  <span>
    <%= participant.name %> joined your game <%= game.name %> |
    <% if notification %>
      <%= link_to "Close", notification_destroy_path(notification), data: {turbo_method: :delete} %>
    <% end %>
  </span>
</div>
<% end %>

app/views/notifications/_notification_classifying.html.erb
<%= turbo_frame_tag "#{dom_id(notification)}_notification" do %>
  <% if notification.subject_type == "Friendship" %>
    <%= render 'notifications/friendship_notification',
        friendship: notification.subject %>
  <% elsif notification.subject_type == "GameInvite" %>
    <%= render 'notifications/game_invite_notification',
        sender: notification.subject.sender,
        game: notification.subject.game,
        notification: notification.subject%>
  <% end %>
<% end %>

app/views/notifications/_notifications.html.erb
<% notifications.each do |notification| %>
  <%= render "notifications/notification_classifying", notification: notification, user: user%>
<% end %>

app/views/notifications/_participant_notification.html.erb
<% if participant %>
<div>
  <% if unread %>
    <span> Unread </span>
  <% end %>
  <span>
    <%= participant.name %> joined your game <%= game.name %> |
    <% if notification %>
      <%= link_to "Close", notification_destroy_path(notification), data: {turbo_method: :delete} %>
    <% end %>
  </span>
</div>
<% end %>