config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #                                 registrations: 'users/registrations',
  #                                 sessions: 'users/sessions'
  #                               }

  resources :registrations
  resources :sessions
  resources :password
  resource :password_reset

  patch '/id/:id/edit', to: 'registrations#update', as: :edit_user_info

  resources :games

  root to: 'home#home'

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get 'games', to: 'games#index'
        get 'games/:id', to: 'games#show'
        get 'id/:id', to: 'profiles#show'
      end
    end
  end


  patch '/games/:id/choose_winner', to: 'games#choose_winner', as: :choose_winner
  post '/games/:id', to: 'participants#create', as: :game_participants
  get '/id/:id', to: 'profiles#show', as: :user_profile
  get '/id/:id/friends', to: 'profiles#friends', as: :user_friends
  post '/id/:id', to: 'friendships#create', as: :user_friendships
  patch '/id/:id', to: 'friendships#update', as: :friendship
  delete '/notification/:id', to: 'notifications#destroy', as: :notification_destroy

  post '/games/:id/game_invites', to: 'notifications#create_user_invite', as: :game_invites

  post '/game_invites/:id/accept', to: 'notifications#accept_invite', as: :accept_invite
  delete '/game_invites/:id/decline', to: 'notifications#decline_invite', as: :decline_invite

  post  '/frienships/create', to: 'notifications#send_friendship_request', as: :send_friendship_request
  patch '/friendships/:id/accept', to: 'notifications#accept_friendship', as: :accept_friendship
  patch '/friendships/:id/decline', to: 'notifications#decline_friendship', as: :decline_friendship

  # oauth
  get '/auth/discord/callback', to: 'omniauth#discord', as: :discord_login
  get '/auth/github/callback', to: 'omniauth#github', as: :github_login

  # webhooks

  get 'pricing', to: 'stripe/checkout#pricing'
  post 'stripe/webhooks', to: 'stripe/webhooks#create'
  post 'stripe/checkout', to: 'stripe/checkout#create'
  get 'stripe/success', to: 'stripe/checkout#success'
  get 'stripe/failure', to: 'stripe/checkout#failure'
  post 'stripe/billing_portal', to: 'stripe/billing_portal#create'
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord # :nodoc:
  validates :name, :number, presence: true

  belongs_to :user, optional: true
  belongs_to :creator, class_name: 'User', optional: true
  belongs_to :game

  after_create_commit { delete_game_invite_notifications }

  private

  def delete_game_invite_notifications
  #   return unless user && game.game_invites.pluck(:receiver_id).include?(user.id)

  #   user.notifications.each do |notification|
  #     params = notification.to_notification
  #     notification.destroy if params.params[:message].game == game
  #   end
  end

end

app/controllers/participants_controller.rb
# frozen_string_literal: true

class ParticipantsController < ApplicationController # :nodoc:
  include ActionView::RecordIdentifier
  before_action :set_game

  def create
    authorize @game, :full?
    @participant = @game.participants.new(participant_params)
    @user = current_user

    @eligible_friends = @user.find_eligible_friends_for_game(@game) if current_user

    respond_to do |format|
      if @participant.save
        format.turbo_stream do
          render turbo_stream: [
            guest_form_frame_tag
          ]
        end
        game_participants_list_stream
        game_member_counter_stream
        remove_join_responsive_icon if @game.participants.count == @game.members
      else
        format.turbo_stream do
          render turbo_stream:
          raise_frame_tag_error
        end
      end
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def participant_params
    params.required(:participant).permit(:game_id, :user_id, :name, :number, :created_by, :creator_id)
  end


  def raise_frame_tag_error
    turbo_stream.update('flash_messages', partial: 'layouts/flash_messages', locals: { alert: "Can't join this game, number and username can't be blank"})
  end

  def guest_form_frame_tag
    if @user
      turbo_stream.update 'joining',  partial: 'games/join', locals: { game: @game, user: current_user, friends: @user.find_eligible_friends_for_game(@game) }
    else
      turbo_stream.update 'joining',  partial: 'games/join', locals: { game: @game, user: current_user }
    end
  end

  def guest_form_stream
    if @participant.guest?
      Turbo::StreamsChannel.broadcast_update_to "#{dom_id(@game)}", target: 'guest_form', partial: 'participants/new_guest', locals: { game: @game, participant: Participant.new }
    else
      Turbo::StreamsChannel.broadcast_update_to "#{dom_id(@game)}", target: 'user_guest_form', partial: 'participants/new_guest_user', locals: { user: @participant.creator, game: @game, participant: Participant.new }
    end
  end

  def participants_list_stream
    Turbo::StreamsChannel.broadcast_append_to "#{dom_id(@game)}", target: 'participants', partial: 'participants/participant', locals: { participant: @participant, game: @game }
  end

  def game_participants_list_stream
    Turbo::StreamsChannel.broadcast_append_to "games", target: "#{dom_id(@game)}_participants", partial: 'participants/participant', locals: { participant: @participant, game: @game }
  end

  def win_selector_stream
    Turbo::StreamsChannel.broadcast_update_to "#{dom_id(@game)}", target: 'win_selector', partial: 'participants/win_selector', locals: { participants: @game.participants , game: @game }
  end

  def game_member_counter_stream
    Turbo::StreamsChannel.broadcast_update_to 'games', target: 'participants_counter', html: @game.participants.count
    Turbo::StreamsChannel.broadcast_update_to "#{dom_id(@game)}", target: 'participants_counter', html: @game.participants.count
  end

  def remove_joining_aside_stream
    Turbo::StreamsChannel.broadcast_remove_to "#{dom_id(@game)}", target: 'joining'
  end

  def remove_user_invite_stream
    Turbo::StreamsChannel.broadcast_remove_to "#{dom_id(@game)}", target: "user_#{@participant.user_id}"
  end

  def remove_join_user_button_stream
    Turbo::StreamsChannel.broadcast_remove_to "#{dom_id(@game)}", target: "#{dom_id(@game)}_#{dom_id(@participant.user)}_join_button"
  end

  def remove_join_responsive_icon
    Turbo::StreamsChannel.broadcast_remove_to "games", target: "#{dom_id(@game)}_join_icon"
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_autorized.html.erb
<div id = "<%=dom_id(game)%>_<%=dom_id(current_user)%>_join_button">
  <%= form_with(model: [game, Participant.new]) do |form| %>
        <%= form.hidden_field :name, value: current_user.username%>
        <%= form.hidden_field :number, value: current_user.number%>
        <%= form.hidden_field :user_id, value: current_user.id%>
    <div>
      <%= form.submit "Join" %>
    </div>
  <% end %>
</div>

app/views/participants/_autorized_avatar.html.erb
<div data-controller = "popover"
     class = "group inline-block relative">
<% if user&.avatar&.attached? %>
    <%=link_to (image_tag (user.avatar),
                              class: "object-cover w-16 h-16"),
                              "/id/#{user.id}", data: { action: "mouseenter->popover#show mouseout->popover#hide mouseleave->popover#hide" ,
                                                        turbo: :false } %>
    <%= render "profiles/mini_profile", user: user %>

<% else %>
    <%= link_to (image_tag "guestavatar1.png",
                            class: "object-cover w-16 h-16"),
                            "/id/#{user.id}", data: { action: "mouseenter->popover#show mouseout->popover#hide mouseleave->popover#hide",
                                                      turbo: :false }%>
    <%= render "profiles/mini_profile", user: user %>
<% end %>
</div>

app/views/participants/_blank_avatar.html.erb
<div data-controller = "hover" class = 'relative'>
  <div class = "flex flex-row relative">
    <% if user && user.avatar.attached? %>
      <%= link_to((image_tag 'guestavatar1.png', class: "object-cover w-16 h-16 duration-500 relative opacity-10 hover:opacity-60", data: { hover_target: "image", hover_avatar_value: "#{url_for(user.avatar.blob)}" }), game)%>
      <%= link_to((image_tag current_user.avatar, class: "object-cover w-16 h-16"), game, class: "absolute transition ease-in-out duration-500 opacity-0 hover:opacity-60", data: { hover_target: "image", action: "mouseover->hover#mouseOver mouseout->hover#mouseOut"}) if current_user%>
    <% else %>
      <%= link_to((image_tag 'guestavatar1.png', class: "object-cover w-16 h-16 duration-500 relative opacity-10 hover:opacity-60", data: { hover_target: "image", hover_avatar_value: "/assets/guestavatar1.png" }), game)%>
    <% end %>

  </div>
</div>

app/views/participants/_guest_avatar.html.erb
<%= image_tag "guestavatar1.png",class: "w-16 h-16" %>

app/views/participants/_member_counter.html.erb
<%= game.participants.count %>/<%= game.members %>

app/views/participants/_new_guest.html.erb
<div id = "guest_form">
  <%= form_with(model: [game, participant]) do |form| %>

    <div>
      <strong> Name </strong>
      <div>
        <%= form.text_field :name%>
      </div>
    </div>

    <div>
      <strong> Number </strong>
      <div>
        <%= form.text_field :number%>
      </div>
    </div>

    <div>
      <%= form.submit "Join" %>
    </div>

  <% end %>
</div>

app/views/participants/_new_guest_user.html.erb
<div id = "user_guest_form">
  <%= form_with(model: [game, participant]) do |form| %>

    <div>
      <strong> Name </strong>
      <div>
        <%= form.text_field :name%>
      </div>
    </div>

    <div>
      <strong> Number </strong>
      <div>
        <%= form.text_field :number%>
      </div>

      <%= form.submit "Join" %>
    </div>

  <% end %>
</div>

app/views/participants/_participant.html.erb
<%= turbo_frame_tag dom_id(participant) do %>
  <div class = 'flex flex-col justify-center relative items-center mr-4'>
  <%# 'flex flex-row' for game/id view %>
  <% if participant.user.present?%>
    <%= render "participants/autorized_avatar", user: participant.user, class: 'align-middle' %>
    <%= participant.user.username.truncate(8) %>
  <% else %>
    <%= render "participants/guest_avatar" %>
    <%= participant.name.truncate(8) %>
  <% end %>

  </div>
<% end %>

app/views/participants/_win_selector.html.erb
    <%= form_with(model: game, url: choose_winner_path(game), method: "patch") do |form| %>
      <h3>  Choose a winner </h3>
        <%= form.select :winner_id, participants.each.map { |one| [one.name, one.id] } %>
      <div><%= form.submit "Finish" %></div>
      </p>
    <% end %>

app/views/participants/_winner.html.erb
<% if winner&.user&.avatar&.present? %>
  <h3> Winner <div> <%= link_to (image_tag (winner.user.avatar), class: "avatar"), "/id/#{winner.user.id}" %> - <%= winner.name %> </div> </h3>
<% elsif winner&.user%>
  <h3> Winner <div> <%= link_to (image_tag "guestavatar1.png",class: "avatar"), "/id/#{winner.user.id}" %> - <%= winner.name %> </div></h3>
<% elsif winner%>
  <h3> Winner <div> <%= image_tag "guestavatar1.png",class: "avatar" %> - <%= winner.name %> </div></h3>
<% end %>

app/views/participants/create.turbo_stream.erb
<% if @participant.id.present? %>
<%= turbo_stream.append("participants_game_#{@game.id}",
                          partial: 'participants/participant',
                          locals: { game: @game, participant: @participant })%>

<%= turbo_stream.update("game_#{@game.id}_counter",
                         partial: 'participants/member_counter',
                         locals: { game: @game })%>

<%= turbo_stream.update("game_#{@game.id}_joining",
                        partial: 'games/join',
                        locals: { game: @game, user: current_user, friends: @eligible_friends }) %>

<%= turbo_stream.update("game_#{@game.id}_win_selector",
                        partial: 'participants/win_selector',
                        locals: { game: @game, participants: @game.participants })%>

<% else %>
  <%= turbo_stream.update('flash_messages',
                            partial: 'layouts/flash_messages',
                            locals: { alert: "Can't join this game, number and username can't be blank"})%>
<% end %>