config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users, controllers: {
  #                                 registrations: 'users/registrations',
  #                                 sessions: 'users/sessions'
  #                               }

  resources :registrations
  resources :sessions
  resources :password
  resource :password_reset

  patch '/id/:id/edit', to: 'registrations#update', as: :edit_user_info

  resources :games

  root to: 'home#home'

  namespace :api do
    namespace :v1 do
      defaults format: :json do
        get 'games', to: 'games#index'
        get 'games/:id', to: 'games#show'
        get 'id/:id', to: 'profiles#show'
      end
    end
  end


  patch '/games/:id/choose_winner', to: 'games#choose_winner', as: :choose_winner
  post '/games/:id', to: 'participants#create', as: :game_participants
  get '/id/:id', to: 'profiles#show', as: :user_profile
  get '/id/:id/friends', to: 'profiles#friends', as: :user_friends
  post '/id/:id', to: 'friendships#create', as: :user_friendships
  patch '/id/:id', to: 'friendships#update', as: :friendship
  delete '/notification/:id', to: 'notifications#destroy', as: :notification_destroy

  post '/games/:id/game_invites', to: 'notifications#create_user_invite', as: :game_invites

  post '/game_invites/:id/accept', to: 'notifications#accept_invite', as: :accept_invite
  delete '/game_invites/:id/decline', to: 'notifications#decline_invite', as: :decline_invite

  post  '/frienships/create', to: 'notifications#send_friendship_request', as: :send_friendship_request
  patch '/friendships/:id/accept', to: 'notifications#accept_friendship', as: :accept_friendship
  patch '/friendships/:id/decline', to: 'notifications#decline_friendship', as: :decline_friendship

  # oauth
  get '/auth/discord/callback', to: 'omniauth#discord', as: :discord_login
  get '/auth/github/callback', to: 'omniauth#github', as: :github_login

  # webhooks

  get 'pricing', to: 'stripe/checkout#pricing'
  post 'stripe/webhooks', to: 'stripe/webhooks#create'
  post 'stripe/checkout', to: 'stripe/checkout#create'
  get 'stripe/success', to: 'stripe/checkout#success'
  get 'stripe/failure', to: 'stripe/checkout#failure'
  post 'stripe/billing_portal', to: 'stripe/billing_portal#create'
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord # :nodoc:
  belongs_to :receiver, class_name: 'User', inverse_of: :friendships_reqs, foreign_key: 'receiver_id'
  belongs_to :sender, class_name: 'User', inverse_of: :friendships, foreign_key: 'sender_id'

  enum status: %i[pending accepted]

  has_one :notification, as: :subject, dependent: :destroy

  scope :with_users_avatars, -> { includes(receiver: :avatar_attachment, sender: :avatar_attachment) }
  # scope :not_request, -> { where(request: false) }
  after_create_commit { create_notification }

  def accept
    accepted!
    notification.destroy
  end

  def decline
    destroy
    notification.destroy

  end

  private

  def create_notification
    Notification.create(user_id: receiver.id, subject_type: self.class, subject_id: id)
  end
end

app/views/friendships/_add_friend.html.erb
<%= form_with(model: [user, Friendship.new], url: send_friendship_request_path) do |form| %>
      <%= form.hidden_field :sender_id, value: current_user.id%>
      <%= form.hidden_field :receiver_id, value: user.id%>
  <div>
    <%= form.submit "Add friend" %>
  </div>

<% end %>

app/views/friendships/_friendship.html.erb
    <% if friendship.receiver == user %>
      <%= turbo_frame_tag "#{dom_id(friendship)}" do %>
      <div class = 'flex flex-initial items-center p-2 pr-10'>
      <% if friendship.sender&.avatar&.attached? %>
          <%= link_to (image_tag friendship.sender.avatar, class: "rounded-md border-2 border-#{friendship.sender.online? ? 'green' : 'gray'}-500 object-cover w-12 h-12 "), "/id/#{friendship.sender_id}", data: { turbo: :false }%>
        <% else %>
          <%= link_to (image_tag "guestavatar1.png", class: "rounded-md border-2 border-#{friendship.sender.online? ? 'green' : 'gray'}-500 object-cover w-12 h-12 "), "/id/#{friendship.sender_id}", data: { turbo: :false }%>
        <% end %>
      <%= friendship.sender.username %>
      </div>
      <% end %>
    <% else %>
      <%= turbo_frame_tag "#{dom_id(friendship)}" do %>
      <div class = 'flex items-center p-2 pr-10'>
        <% if friendship.receiver&.avatar&.attached? %>
          <%= link_to (image_tag friendship.receiver.avatar, class: "rounded-md border-2 border-#{friendship.receiver.online? ? 'green' : 'gray'}-500 object-cover w-12 h-12 "), "/id/#{friendship.receiver_id}", data: { turbo: :false }%>
        <% else %>
          <%= link_to (image_tag "guestavatar1.png", class: "rounded-md border-2 border-#{friendship.receiver.online? ? 'green' : 'gray'}-500 object-cover w-12 h-12 "), "/id/#{friendship.receiver_id}", data: { turbo: :false }%>
        <% end %>
      <%= friendship.receiver.username %>
      </div>
      <% end %>
    <% end %>